### PR TITLE
Update packages path in install-source.sh

### PR DESCRIPTION
**Pull request by Starbix**

### CODE REVIEW

**Comment by diego-vieira** [comment]
it would be amazing if this could be merged please

**Comment by octavianx** [comment]
👍

**Comment by octavianx** [comment]
I met with the same problem.  fixed by this  manuver

**Comment by akoval54** [comment]
Just fixed the same manually. Raspberry Pi.

**Comment by aluttik** [comment]
The issue has been solved, thanks

**Pull request closed without merging**
